name: gravity_ui
description: Gravity UI on Flutter.
version: 0.0.1
repository: "https://github.com/proteye/flutter-gravity-ui"

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
